# Slovak data

In [3]:
import pandas as pd
from IPython.display import Markdown;
import numpy

## slovak_immigration.csv

In [8]:
df = pd.read_csv("../../Data/slovakia/slovak_immigration.csv")
country_codes = pd.read_csv('../../Data/country_region_subregion_codes.csv')

merged_df = df.merge(country_codes, left_on='citizen', right_on='alpha-2', how='left')

merged_df['geo'] = 'Slovakia'
merged_df['Geopolitical entity (reporting)'] = 'SVK'

merged_df = merged_df.drop(columns=['citizen', 'name', 'alpha-2', 'country-code','iso_3166-2','intermediate-region','region-code','sub-region-code','intermediate-region-code', 'STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'freq', 'Time frequency', 'agedef', 'Age definition', 'Age class', 'unit', 'Unit of measure', 'sex', 'Time'])
merged_df = merged_df.rename(columns={'Country of citizenship': 'citizen_country', 'alpha-3': 'citizen_ISO3', 'region': 'citizen_region','sub-region': 'citizen_sub_region', 'geo': 'country', 'Geopolitical entity (reporting)': 'country_ISO3', 'TIME_PERIOD': 'year', 'OBS_VALUE': 'count', 'Sex': 'sex'})

columns_order = list(merged_df.columns)
columns_order.remove('citizen_ISO3')
columns_order.remove('citizen_region')
columns_order.remove('citizen_sub_region')
columns_order.insert(1, 'citizen_ISO3')
columns_order.insert(2, 'citizen_region')
columns_order.insert(3, 'citizen_sub_region')
merged_df = merged_df[columns_order]

merged_df = merged_df.iloc[:, :-5]

display(merged_df.head())

file_save_path = "../../Data/slovakia/slovak_immigration.csv"
merged_df.to_csv(file_save_path,index=False)

,citizen_country,citizen_ISO3,citizen_region,citizen_sub_region,age,sex,country,country_ISO3,year,count
0,Andorra,AND,Europe,Southern Europe,TOTAL,Females,Slovakia,SVK,2008,0
1,Andorra,AND,Europe,Southern Europe,TOTAL,Females,Slovakia,SVK,2009,0
2,Andorra,AND,Europe,Southern Europe,TOTAL,Females,Slovakia,SVK,2010,0
3,Andorra,AND,Europe,Southern Europe,TOTAL,Females,Slovakia,SVK,2011,0
4,Andorra,AND,Europe,Southern Europe,TOTAL,Females,Slovakia,SVK,2012,0

## slovak_emigration.csv

In [3]:
df = pd.read_csv("../../Data/slovakia/slovak_emigration.csv")
country_codes = pd.read_csv('../../Data/country_region_subregion_codes.csv')

merged_df = df.merge(country_codes, left_on='partner', right_on='alpha-2', how='left')

merged_df['geo'] = 'Slovakia'
merged_df['Geopolitical entity (reporting)'] = 'SVK'

merged_df = merged_df.drop(columns=['partner', 'name', 'alpha-2', 'country-code','iso_3166-2','intermediate-region','region-code','sub-region-code','intermediate-region-code', 'STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'freq', 'Time frequency', 'agedef', 'Age definition', 'Age class', 'unit', 'Unit of measure', 'sex', 'Time'])
merged_df = merged_df.rename(columns={'Geopolitical entity (partner)': 'target_country', 'alpha-3': 'target_ISO3', 'region': 'target_region','sub-region': 'target_sub_region', 'geo': 'country', 'Geopolitical entity (reporting)': 'country_ISO3', 'TIME_PERIOD': 'year', 'OBS_VALUE': 'count', 'Sex': 'sex'})

columns_order = list(merged_df.columns)
columns_order.remove('target_ISO3')
columns_order.remove('target_region')
columns_order.remove('target_sub_region')
columns_order.insert(1, 'target_ISO3')
columns_order.insert(2, 'target_region')
columns_order.insert(3, 'target_sub_region')
merged_df = merged_df[columns_order]

merged_df = merged_df.iloc[:, :-5]

display(merged_df.head())

file_save_path = "../../Data/slovakia/slovak_emigration.csv"
merged_df.to_csv(file_save_path,index=False)

,target_country,target_ISO3,target_region,target_sub_region,age,sex,country,country_ISO3,year,count
0,Andorra,AND,Europe,Southern Europe,TOTAL,Females,Slovakia,SVK,1998,0
1,Andorra,AND,Europe,Southern Europe,TOTAL,Females,Slovakia,SVK,1999,0
2,Andorra,AND,Europe,Southern Europe,TOTAL,Females,Slovakia,SVK,2000,0
3,Andorra,AND,Europe,Southern Europe,TOTAL,Females,Slovakia,SVK,2002,0
4,Andorra,AND,Europe,Southern Europe,TOTAL,Females,Slovakia,SVK,2003,0

## slovak_temporary_protection.csv

In [ ]:
df = pd.read_csv("../../Data/slovakia/slovak_temporary_protection.csv")
country_codes = pd.read_csv('../../Data/country_region_subregion_codes.csv')

merged_df = df.merge(country_codes, left_on='citizen', right_on='alpha-2', how='left')

merged_df['geo'] = 'Slovakia'
merged_df['Geopolitical entity (reporting)'] = 'SVK'

merged_df = merged_df.drop(columns=['citizen', 'name', 'alpha-2', 'country-code','iso_3166-2','intermediate-region','region-code','sub-region-code','intermediate-region-code', 'STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'freq', 'Time frequency', 'Age class', 'unit', 'Unit of measure', 'sex', 'Time'])
merged_df = merged_df.rename(columns={'Country of citizenship': 'citizen_country', 'alpha-3': 'citizen_ISO3', 'region': 'citizen_region','sub-region': 'citizen_sub_region', 'geo': 'country', 'Geopolitical entity (reporting)': 'country_ISO3', 'TIME_PERIOD': 'year', 'OBS_VALUE': 'count', 'Sex': 'sex'})

columns_order = list(merged_df.columns)
columns_order.remove('citizen_ISO3')
columns_order.remove('citizen_region')
columns_order.remove('citizen_sub_region')
columns_order.insert(1, 'citizen_ISO3')
columns_order.insert(2, 'citizen_region')
columns_order.insert(3, 'citizen_sub_region')
merged_df = merged_df[columns_order]

merged_df = merged_df.iloc[:, :-5]

display(merged_df.head())

file_save_path = "../../Data/slovakia/slovak_temporary_protection.csv"
merged_df.to_csv(file_save_path,index=False)

,citizen_country,citizen_ISO3,citizen_region,citizen_sub_region,sex,age,country,country_ISO3,year,count
0,Andorra,AND,Europe,Southern Europe,Females,TOTAL,Slovakia,SVK,2022-03,0
1,Andorra,AND,Europe,Southern Europe,Females,TOTAL,Slovakia,SVK,2022-04,0
2,Andorra,AND,Europe,Southern Europe,Females,TOTAL,Slovakia,SVK,2022-05,0
3,Andorra,AND,Europe,Southern Europe,Females,TOTAL,Slovakia,SVK,2022-06,0
4,Andorra,AND,Europe,Southern Europe,Females,TOTAL,Slovakia,SVK,2022-07,0